Rework the systemd units.

diff --git a/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery b/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery
--- a/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery
+++ b/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery
@@ -22,7 +22,33 @@ cleanup_before_exit () {
 tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
 # trap catches the exit signal and runs the specified function
 trap cleanup_before_exit EXIT
+# be in our directory
+cd "${tmpdir}"
 
+
+#
+# Per instance? Run all scripts
+
+if [ $# -ne 0 ]; then
+
+  instance="${1}"
+
+  logger -t "dirsrv-autodiscovery@${instance}" "running autodiscovery for directory server instance ${instance}..."
+
+  find "$0.d" -type f -executable | sort | \
+  while read x; do
+    "$x" "${instance}" < /dev/null || touch error;
+  done
+
+  if test ! -f "error"; then
+    logger -t "dirsrv-autodiscovery@${instance}" "completed autodiscovery for directory server instance ${instance}."
+    exit 0
+  else
+    logger -t "dirsrv-autodiscovery@${instance}" "failed autodiscovery for directory server instance ${instance}."
+    exit 1
+  fi
+
+fi
 
 
 #
@@ -310,8 +336,27 @@ while read line; do
     create_instance "${instance}"
     logger -t dirsrv-autodiscovery "created directory server instance ${instance}."
 
-    systemctl enable "dirsrv@${instance}"
-    systemctl start "dirsrv@${instance}"
+    if test -f "$line/disabled.bin"; then
+
+      systemctl disable "dirsrv-autodiscovery@${instance}"
+      systemctl disable "dirsrv@${instance}"
+      systemctl disable "dirsrv-postdiscovery@${instance}"
+
+      systemctl stop "dirsrv-autodiscovery@${instance}"
+      systemctl stop "dirsrv@${instance}"
+      systemctl stop "dirsrv-postdiscovery@${instance}"
+
+    else
+
+      systemctl enable "dirsrv-autodiscovery@${instance}"
+      systemctl enable "dirsrv@${instance}"
+      systemctl enable "dirsrv-postdiscovery@${instance}"
+
+      systemctl start "dirsrv-autodiscovery@${instance}"
+      systemctl start "dirsrv@${instance}"
+      systemctl start "dirsrv-postdiscovery@${instance}"
+
+    fi
 
     rm -f "$line/added"
 
@@ -320,17 +365,45 @@ while read line; do
 
     instance="$(head $line/instance.txt)"
 
+    if test -f "$line/disabled.bin"; then
+
+      systemctl disable "dirsrv-autodiscovery@${instance}"
+      systemctl disable "dirsrv@${instance}"
+      systemctl disable "dirsrv-postdiscovery@${instance}"
+
+      systemctl stop "dirsrv-autodiscovery@${instance}"
+      systemctl stop "dirsrv@${instance}"
+      systemctl stop "dirsrv-postdiscovery@${instance}"
+
+    else
+
+      systemctl enable "dirsrv-autodiscovery@${instance}"
+      systemctl enable "dirsrv@${instance}"
+      systemctl enable "dirsrv-postdiscovery@${instance}"
+
+      systemctl start "dirsrv-autodiscovery@${instance}"
+      systemctl start "dirsrv@${instance}"
+      systemctl start "dirsrv-postdiscovery@${instance}"
+
+    fi
+
+    rm -f "$line/updated"
+
   # remove old instances
   elif test -f "$line/removed"; then
 
-    # stop instance, but only if no error was created making the instance
-    if test ! -f "$line/error"; then
-      logger -t dirsrv-autodiscovery "removing directory server instance ${instance}..."
-      systemctl stop "dirsrv@${instance}"
-      systemctl disable "dirsrv@${instance}"
-      dsctl "${instance}" remove --do-it
-      logger -t dirsrv-autodiscovery "removed directory server instance ${instance}."
-    fi
+    logger -t dirsrv-autodiscovery "removing directory server instance ${instance}..."
+
+    systemctl disable "dirsrv-autodiscovery@${instance}"
+    systemctl disable "dirsrv@${instance}"
+    systemctl disable "dirsrv-postdiscovery@${instance}"
+
+    systemctl stop "dirsrv-autodiscovery@${instance}"
+    systemctl stop "dirsrv@${instance}"
+    systemctl stop "dirsrv-postdiscovery@${instance}"
+
+    dsctl "${instance}" remove --do-it
+    logger -t dirsrv-autodiscovery "removed directory server instance ${instance}."
 
     # remove folder
     rm -f "${target}"/*
@@ -341,9 +414,4 @@ while read line; do
 
 done
 
-
-#
-# Run all scripts
-
-find "$0.d" -type f -executable -exec {} \; || true
 
diff --git a/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery b/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery
--- a/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery
+++ b/device-389ds-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery
@@ -8,136 +8,45 @@
 
 set -e
 
-#
-# Silence warnings with runuser.
-cd /tmp
-
 
 #
-# Update ldap instances
-
-find /etc/device/services/ldap-server/instance/ -mindepth 1 -maxdepth 1 -type l | \
-while read line; do
-
-  if test ! -f "$line/instance.txt"; then
-    continue;
+# Handle the cleanup
+# ------------------
+cleanup_before_exit () {
+  if [ -d "${tmpdir}" ]; then
+    rm -rf "${tmpdir}"
   fi
-  instance="$(head $line/instance.txt)"
-
-  # make sure autobind is enabled
-  logger -t dirsrv-postdiscovery "enabling directory server autobind on instance ${instance}..."
-  retry --until=success dsconf "ldapi://%2frun%2fslapd-${instance}.socket" config replace nsslapd-ldapimaptoentries=on nsslapd-ldapiuidnumbertype=uidNumber nsslapd-ldapigidnumbertype=gidNumber nsslapd-ldapientrysearchbase=ou=people,cn=config || echo "Could not enable autobind"
-  logger -t dirsrv-postdiscovery "enabled directory server autobind on instance ${instance}."
-
-  # make sure replication is present
-  logger -t dirsrv-postdiscovery "enabling directory server replication on instance ${instance}..."
-
-  replication_ldif="replication.ldif"
-
-  cat > ${replication_ldif} <<-EOF
-# create the supplier bind dn
-dn: cn=Replication Managers,cn=config
-objectClass: top
-objectClass: groupOfUniqueNames
-cn: Replication Managers
-nsIdleTimeout: 0
-
-EOF
-
-  cat ${replication_ldif} | /usr/bin/ldapadd -H "ldapi://%2frun%2fslapd-${instance}.socket" -Y EXTERNAL 2> /dev/null || true
-
-  logger -t dirsrv-postdiscovery "enabled directory server replication on instance ${instance}."
-
-done
-
-
-#
-# Add/update/remove ldap backends/suffixes
-
-find /etc/device/services/ldap-server/suffix/ -mindepth 1 -maxdepth 1 -type l | \
-while read line; do
-
-  target=$(readlink -f "$line")
-
-  if test ! -f "$line/name.txt"; then
-    continue;
-  fi
-  bename="$(head $line/name.txt)"
-
-  if test ! -f "$line/suffix.txt"; then
-    continue;
-  fi
-  suffix="$(head $line/suffix.txt)"
-
-  if [ ! -e "$line/instance.d/instance.txt" ]; then
-    continue;
-  fi
-  instance="$(head $line/instance.d/instance.txt)"
-
-  # add new instances
-  if test -f "$line/added"; then
-
-    if test ! -d "/etc/dirsrv/slapd-${instance}"; then
-      logger -t dirsrv-postdiscovery "ignoring directory server backend ${bename} with suffix ${suffix}: instance ${instance} does not exist."
-      continue
-    fi
-
-    # add instance
-    logger -t dirsrv-postdiscovery "adding directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
-    dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend create --suffix "${suffix}" --be-name "${bename}" --create-suffix || echo "Could not create suffix" > "$line/error"
-    if test ! -f "$line/error"; then
-      logger -t dirsrv-postdiscovery "added directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
-    else
-      logger -t dirsrv-postdiscovery "failed to add directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
-    fi
-
-    rm -f "$line/added"
-
-  # update instances
-  elif test -f "$line/updated"; then
-
-
-    rm -f "$line/updated"
-
-  # remove old instances
-  elif test -f "$line/removed"; then
-
-    # remove instance, but only if no error was created making the database
-    if test ! -f "$line/error" -a -d "/etc/dirsrv/slapd-${instance}"; then
-      logger -t dirsrv-postdiscovery "removing directory server backend ${bename} with suffix ${suffix} to instance ${instance}..."
-      expect <<- EOF || echo "Could not remove suffix" > "$line/error"
-set timeout -1
-spawn dsconf "ldapi://%2frun%2fslapd-${instance}.socket" backend delete "${bename}"
-match_max 100000
-expect {
-  "Type 'Yes I am sure' to continue: " {
-    send -- "Yes I am sure"
-    expect -exact "Yes I am sure"
-    send -- "\r"
-    expect eof
-  }
-  eof {
-    exit 1
-  }
 }
-EOF
-      if test ! -f "$line/error"; then
-        logger -t dirsrv-postdiscovery "removed directory server backend ${bename} with suffix ${suffix} to instance ${instance}."
-      else
-        logger -t dirsrv-postdiscovery "failed to remove directory server backend ${bename} with suffix ${suffix} to instance ${instance}, forgetting this suffix."
-      fi
-    fi
+# be in a temporay workspace (this works on linux and macosx)
+tmpdir=`mktemp -d 2>/dev/null || mktemp -d -t 'tmpdir'`
+# trap catches the exit signal and runs the specified function
+trap cleanup_before_exit EXIT
+# be in our directory
+cd "${tmpdir}"
 
-    # remove folder
-    rm -f "${target}"/*
-    rmdir "${target}"
-    rm -f "${line}"
-  fi
 
-done
 
 #
-# Run all scripts
+# Per instance? Run all scripts
 
-find "$0.d" -type f -executable -exec {} \; || true
+if [ $# -ne 0 ]; then
+
+  instance="${1}"
+
+  logger -t "dirsrv-postdiscovery@${instance}" "running postdiscovery for directory server instance ${instance}..."
+
+  find "$0.d" -type f -executable | sort | \
+  while read x; do
+    "$x" "${instance}" < /dev/null || touch error;
+  done
+
+  if test ! -f "error"; then
+    logger -t "dirsrv-postdiscovery@${instance}" "completed postdiscovery for directory server instance ${instance}."
+    exit 0
+  else
+    logger -t "dirsrv-postdiscovery@${instance}" "failed postdiscovery for directory server instance ${instance}."
+    exit 1
+  fi
+
+fi
 
