Add first pass at incoming replication.

diff --git a/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery-tls b/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery-tls
--- a/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery-tls
+++ b/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-postdiscovery-tls
@@ -26,8 +26,38 @@ while read line; do
     tls_dns="${hostname}"
   fi
 
+  # remove old instances
+  if test -f "$line/removed"; then
+
+    target=$(readlink -f "$line")
+
+    if test ! -f "$line/disabled.bin"; then
+
+      logger -t dirsrv-postdiscovery "disabling directory server tls on instance ${instance}..."
+
+      dsconf "ldapi://%2frun%2fslapd-${instance}.socket" security disable || echo "Could not disable tls" > "$line/error"
+
+      if test ! -f "$line/error"; then
+        logger -t dirsrv-postdiscovery "disabled directory server tls on instance ${instance}."
+      else
+        logger -t dirsrv-postdiscovery "failed to disable directory server tls for instance ${instance}."
+      fi
+
+      if command -v /usr/bin/firewall-cmd 2>/dev/null; then
+        logger -t "$0" "Notice: disabling firewall for ldaps..."
+        /usr/bin/firewall-cmd --quiet --zone=public --remove-service=ldaps
+        logger -t "$0" "Notice: disabled firewall for ldaps."
+      fi
+
+    fi
+
+    # remove folder
+    rm -f "${target}"/*
+    rmdir "${target}"
+    rm -f "${line}"
+
   # add/update new tls?
-  if test -f "$line/added" -o -f "$line/updated"; then
+  elif test -f "$line/added" -o -f "$line/updated"; then
 
     rm -f "$line/error"
 
@@ -114,36 +144,6 @@ while read line; do
     else
       rm -f "$line/updated"
     fi
-
-  # remove old instances
-  elif test -f "$line/removed"; then
-
-    target=$(readlink -f "$line")
-
-    if test ! -f "$line/disabled.bin"; then
-
-      logger -t dirsrv-postdiscovery "disabling directory server tls on instance ${instance}..."
-
-      dsconf "ldapi://%2frun%2fslapd-${instance}.socket" security disable || echo "Could not disable tls" > "$line/error"
-
-      if test ! -f "$line/error"; then
-        logger -t dirsrv-postdiscovery "disabled directory server tls on instance ${instance}."
-      else
-        logger -t dirsrv-postdiscovery "failed to disable directory server tls for instance ${instance}."
-      fi
-
-      if command -v /usr/bin/firewall-cmd 2>/dev/null; then
-        logger -t "$0" "Notice: disabling firewall for ldaps..."
-        /usr/bin/firewall-cmd --quiet --zone=public --remove-service=ldaps
-        logger -t "$0" "Notice: disabled firewall for ldaps."
-      fi
-
-    fi
-
-    # remove folder
-    rm -f "${target}"/*
-    rmdir "${target}"
-    rm -f "${line}"
 
   # ordinary instance, make sure world can see it
   else
diff --git a/device-389ds-tls-el9/src/main/resources/usr/libexec/device/services/ldap-server/tls/add b/device-389ds-tls-el9/src/main/resources/usr/libexec/device/services/ldap-server/tls/add
--- a/device-389ds-tls-el9/src/main/resources/usr/libexec/device/services/ldap-server/tls/add
+++ b/device-389ds-tls-el9/src/main/resources/usr/libexec/device/services/ldap-server/tls/add
@@ -8,6 +8,20 @@ trap 'rm -rf -- "${tmpdir}"' EXIT
 
 if [ "$1" == "--" ]; then
 
+  counter=2
+  while [ $counter -lt $# ]; do
+    if [ "${!counter}" = "hostname" ]; then
+      ((counter++))
+      redwax-tool --quiet \
+	          --pem-in="/etc/pki/tls/private/*" \
+                  --pem-in="/etc/pki/tls/certs/*" \
+                  --filter=verify \
+                  --filter-hostname="${!counter}" || { echo "Error: could not verify a certificate matching: ${!counter}"; exit 1; }
+      break;
+    fi
+    ((counter+=2))
+  done
+
   /usr/libexec/device-set --add index --index index --port port --fqdn tls-dns --required --fqdn hostname --relation-base /etc/device/services/ldap-server/instance --relation-name instance --relation-suffix .txt --relation instance "$@"
 
   find /etc/device/services/ldap-server/instance/ -mindepth 1 -maxdepth 1 -type l | \
