Run redwax-tool on updates in addition to server creation.

diff --git a/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery-tls b/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery-tls
--- a/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery-tls
+++ b/device-389ds-tls-el9/src/main/resources/usr/libexec/device-389ds-autodiscovery-tls
@@ -15,6 +15,17 @@ while read line; do
     continue;
   fi
 
+  if [ ! -e "$line/hostname.txt" ]; then
+    continue;
+  fi
+  hostname="$(head -n 1 $line/hostname.txt)"
+
+  if [ -e "$line/tls_dns.txt" ]; then
+    tls_dns="$(head -n 1 $line/tls_dns.txt)"
+  else
+    tls_dns="${hostname}"
+  fi
+
   logger -t "$0"  "Notice: creating directory server certmap.conf for ${instance}..."
 
   certmap_conf=`mktemp /etc/dirsrv/slapd-${instance}/certmap.conf.XXXXXX`
@@ -29,6 +40,31 @@ EOF
   mv "${certmap_conf}" "/etc/dirsrv/slapd-${instance}/certmap.conf"
 
   logger -t "$0"  "Notice: created directory server certmap.conf for ${instance}."
+
+  if test ! -f "$line/disabled.bin"; then
+
+    logger -t dirsrv-autodiscovery "Notice: importing directory server certificate/key on instance ${instance}..."
+
+    redwax-tool --pem-in="/etc/pki/tls/private/*" \
+                --pem-in="/etc/pki/tls/certs/ca-bundle.trust.crt" \
+                --pem-in="/etc/pki/tls/certs/*.pem" \
+                --filter=verify \
+                --filter-hostname "${tls_dns}" \
+                --filter-expiry=ignore-leaf \
+                --label-out Server-Cert \
+                --secret-token-out="/etc/dirsrv/slapd-${instance}/pin.txt" \
+                --auto-out \
+                --trust-out \
+                --nss-out=/etc/dirsrv/slapd-${instance}/ || echo "Could not import cert/key for tls" > "$line/error"
+
+    if test ! -f "$line/error"; then
+      logger -t dirsrv-postdiscovery "Notice: imported directory server certificate/key on instance ${instance}."
+    else
+      logger -t dirsrv-postdiscovery "Error: failed to import directory server certificate/key for instance ${instance}."
+      continue
+    fi
+
+  fi
 
 done
 
